"""phase 4 scenario planning

Revision ID: 108ebff8787e
Revises: 2b6e1d4b080c
Create Date: 2026-08-13 15:40:53.554345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108ebff8787e'
down_revision: Union[str, Sequence[str], None] = '2b6e1d4b080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='ck_scenarios_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('baseline_start_date', sa.Date(), nullable=False),
    sa.Column('baseline_end_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('baseline_end_date >= baseline_start_date', name='ck_scenario_end_after_start'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('scenario_operations',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.Enum('ADD_ALLOCATION', 'ADJUST_ALLOCATION', 'REMOVE_ALLOCATION', 'MOVE_ALLOCATION', 'SHIFT_PROJECT', 'AVAILABILITY_OVERRIDE', 'AVAILABILITY_CLEAR', 'ADD_HYPOTHETICAL_RESOURCE', name='ck_scenario_operations_operation_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_operations_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_operations')),
    sa.UniqueConstraint('scenario_id', 'sequence', name='uq_scenario_operation_sequence')
    )
    op.create_index(op.f('ix_scenario_operations_scenario_id'), 'scenario_operations', ['scenario_id'], unique=False)
    # NOTE: autogenerate also proposed dropping and (in downgrade) re-adding
    # ck_allocations_allocation_unit / ck_people_employment_status /
    # ck_projects_status — a known SQLite-reflection false positive (it
    # cannot reliably diff CHECK constraint text on Enum(native_enum=False)
    # columns), unrelated to Phase 4. Removed by hand so this migration only
    # touches the two new scenario tables and doesn't churn Phase 1 schema.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_operations_scenario_id'), table_name='scenario_operations')
    op.drop_table('scenario_operations')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
