"""phase 1 domain foundation

Revision ID: 2b6e1d4b080c
Revises: 
Create Date: 2026-08-10 21:28:51.861448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6e1d4b080c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'INACTIVE', name='ck_people_employment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='ck_projects_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_project_end_after_start'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('allocations',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('allocation_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('allocation_unit', sa.Enum('TOTAL_HOURS', name='ck_allocations_allocation_unit', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocation_hours >= 0', name='ck_allocation_hours_nonnegative'),
    sa.CheckConstraint('end_date >= start_date', name='ck_allocation_end_after_start'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_allocations_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_allocations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations'))
    )
    op.create_index('ix_allocation_person_dates', 'allocations', ['person_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_allocation_project_dates', 'allocations', ['project_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_allocations_person_id'), 'allocations', ['person_id'], unique=False)
    op.create_index(op.f('ix_allocations_project_id'), 'allocations', ['project_id'], unique=False)
    op.create_table('availability_exceptions',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('availability_type', sa.Enum('ANNUAL_LEAVE', 'SICK_LEAVE', 'PUBLIC_HOLIDAY', 'TRAINING', 'COMPANY_EVENT', 'PARENTAL_LEAVE', 'PERSONAL_LEAVE', 'REDUCED_AVAILABILITY', 'OTHER', name='availability_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_availability_end_after_start'),
    sa.CheckConstraint('hours IS NULL OR hours >= 0', name='ck_availability_hours_nonnegative'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_availability_exceptions_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_exceptions'))
    )
    op.create_index(op.f('ix_availability_exceptions_person_id'), 'availability_exceptions', ['person_id'], unique=False)
    op.create_index('ix_availability_person_dates', 'availability_exceptions', ['person_id', 'start_date', 'end_date'], unique=False)
    op.create_table('team_memberships',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_team_memberships_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_memberships_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_memberships')),
    sa.UniqueConstraint('person_id', 'team_id', name='uq_team_membership_person_team')
    )
    op.create_index(op.f('ix_team_memberships_person_id'), 'team_memberships', ['person_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    op.create_table('working_schedules',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_end_date IS NULL OR effective_start_date IS NULL OR effective_end_date >= effective_start_date', name='ck_working_schedule_effective_dates'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_working_schedules_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_schedules'))
    )
    op.create_index(op.f('ix_working_schedules_person_id'), 'working_schedules', ['person_id'], unique=False)
    op.create_table('working_schedule_entries',
    sa.Column('working_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('hours >= 0 AND hours <= 24', name='ck_schedule_entry_hours_range'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_schedule_entry_weekday_range'),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], name=op.f('fk_working_schedule_entries_working_schedule_id_working_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_schedule_entries')),
    sa.UniqueConstraint('working_schedule_id', 'weekday', name='uq_schedule_entry_schedule_weekday')
    )
    op.create_index(op.f('ix_working_schedule_entries_working_schedule_id'), 'working_schedule_entries', ['working_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_schedule_entries_working_schedule_id'), table_name='working_schedule_entries')
    op.drop_table('working_schedule_entries')
    op.drop_index(op.f('ix_working_schedules_person_id'), table_name='working_schedules')
    op.drop_table('working_schedules')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_person_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index('ix_availability_person_dates', table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_person_id'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_allocations_project_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_person_id'), table_name='allocations')
    op.drop_index('ix_allocation_project_dates', table_name='allocations')
    op.drop_index('ix_allocation_person_dates', table_name='allocations')
    op.drop_table('allocations')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
