"""phase 7 skills bottleneck analysis

Revision ID: e79054e949ad
Revises: 3518aa2c92c3
Create Date: 2026-08-17 10:35:38.256430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Autogenerate additionally proposed drop_constraint/create_check_constraint
# operations against ck_allocations_allocation_unit, ck_people_employment_status,
# ck_projects_status, ck_scenario_operations_operation_type, and
# ck_scenarios_status — the same known SQLite CHECK-constraint text-diff
# false positive already documented in ADR 0002/0004/0005/0006 (fires
# identically for untouched enum columns in every prior autogenerate run).
# Removed by hand below; this migration only contains the 3 new tables
# (skills, person_skills, project_skill_requirements) and their indexes
# (docs/adr/0007-phase-7-skills-bottleneck-analysis.md).


# revision identifiers, used by Alembic.
revision: str = 'e79054e949ad'
down_revision: Union[str, Sequence[str], None] = '3518aa2c92c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_table('person_skills',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'WORKING', 'PROFICIENT', 'ADVANCED', 'EXPERT', name='ck_person_skills_proficiency', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_skills_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_person_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_skills')),
    sa.UniqueConstraint('person_id', 'skill_id', name='uq_person_skill_person_skill')
    )
    op.create_index(op.f('ix_person_skills_person_id'), 'person_skills', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_skills_skill_id'), 'person_skills', ['skill_id'], unique=False)
    op.create_table('project_skill_requirements',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_hours', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('minimum_proficiency', sa.Enum('BEGINNER', 'WORKING', 'PROFICIENT', 'ADVANCED', 'EXPERT', name='ck_project_skill_requirements_min_proficiency', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('required_hours > 0', name='ck_project_skill_requirement_hours_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_skill_requirements_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_project_skill_requirements_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_skill_requirements')),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_project_skill_requirement_project_skill')
    )
    op.create_index(op.f('ix_project_skill_requirements_project_id'), 'project_skill_requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_skill_requirements_skill_id'), 'project_skill_requirements', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_skill_requirements_skill_id'), table_name='project_skill_requirements')
    op.drop_index(op.f('ix_project_skill_requirements_project_id'), table_name='project_skill_requirements')
    op.drop_table('project_skill_requirements')
    op.drop_index(op.f('ix_person_skills_skill_id'), table_name='person_skills')
    op.drop_index(op.f('ix_person_skills_person_id'), table_name='person_skills')
    op.drop_table('person_skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
